spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meety_db
    username: postgres
    password: 8965
    //driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true